
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef SRC_ENUM_GTYPES_H_
#define SRC_ENUM_GTYPES_H_
#include <glib-object.h>
G_BEGIN_DECLS
/* enumerations from "parole-button.h" */
GType parole_button_key_get_type (void);
#define ENUM_GTYPE_BUTTON_KEY (parole_button_key_get_type())
G_END_DECLS

#endif /* SRC_ENUM_GTYPES_H_ */

/* Generated data ends here */

